version: '3'

services:
  postgres:
    image: mdillon/postgis:9.5
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=admin
  phppgadmin:
    image: zhajor/docker-phppgadmin
    ports:
      - '5433:80'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    links:
      - postgres
    depends_on:
      - postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres